<<<<<<< HEAD
# Generated by Django 4.0 on 2023-02-12 09:55
=======
# Generated by Django 4.0 on 2023-02-16 06:53
>>>>>>> productmodelview

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sub_slug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='products.catgory')),
            ],
            options={
                'verbose_name': 'my_catgory',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
>>>>>>> productmodelview
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('price', models.IntegerField(help_text='براساس تومان')),
                ('datetime', models.DateTimeField()),
<<<<<<< HEAD
                ('image', models.ImageField(upload_to='')),
=======
                ('color', models.CharField(max_length=100)),
                ('garanti', models.CharField(max_length=110)),
>>>>>>> productmodelview
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('aviable', models.BooleanField(default=True)),
                ('descriptions', models.TextField()),
                ('crated', models.DateTimeField(auto_now_add=True)),
                ('updeted', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='products.Catgory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='propert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsubproper', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Producta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_producta', to='products.image')),
                ('producta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producta', to='products.product')),
                ('propertya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perppertu_producta', to='products.propert')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsub', to='products.product'),
        ),
>>>>>>> productmodelview
    ]
